import React, {useState,useEffect} from "react";
import axios from "axios";
import { useNavigate } from "react-router"
import { useParams } from "react-router";

const Avatar = (props)=>{
    const [user,setUser]= useState({})
    const navi = useNavigate();

    useEffect(()=>{
        axios.get("http://localhost:8000/api/user/logged",{withCredentials:true}).then((res)=>{
            console.log(res.data)
            setUser(res.data)

        }).catch((err)=>{console.log(err)})

    },[])

    const borderGiver=(e,num)=>{
        e.preventDefault();
        var move= document.getElementById(num)
        
        move.classList.add("bordergiverAv")
    }

    const borderTaker=(e,num)=>{
        e.preventDefault();
        var move= document.getElementById(num)
        move.classList.remove("bordergiverAv")
        
    }

    const avatarSelect=(e,ava)=>{
        e.preventDefault()
        axios.put(`http://localhost:8000/api/user/${user._id}`,{profilePic:ava}).then((res)=>{
            navi("/home")
        }).catch((err)=>{console.log(err)})
    }

    return(
        <div>
                        <div className="flexy contain" style={{backgroundColor:"white", width:1500}}>
                <h2 className="contain">Swiz</h2> <img className="slogo contain" src={require(`../photos/symbols/button.jpg`)}/> <h2 className="contain">Card-Game</h2>
            </div>
            <h1>Choose your avatar</h1>
            <button className="btn btn-dark" onClick={(e)=>{
                e.preventDefault()
                navi("/home")
            }}>Use Default</button>
            <div className="contain" style={{backgroundColor:"black",height:500, width:1500, marginTop:20, overflow:"scroll", overflowX:"hidden"}}>
                <h3 style={{color:"white"}}>Male</h3>
                <div className="flexy">
                <img id="m1" onClick={(e)=>{avatarSelect(e,"male/male1.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m1")}} onMouseLeave={(e)=>{borderTaker(e,"m1")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male1.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m2" onClick={(e)=>{avatarSelect(e,"male/male2.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m2")}} onMouseLeave={(e)=>{borderTaker(e,"m2")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male2.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m3" onClick={(e)=>{avatarSelect(e,"male/male3.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m3")}} onMouseLeave={(e)=>{borderTaker(e,"m3")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male3.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m4" onClick={(e)=>{avatarSelect(e,"male/male4.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m4")}} onMouseLeave={(e)=>{borderTaker(e,"m4")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male4.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m5" onClick={(e)=>{avatarSelect(e,"male/male5.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m5")}} onMouseLeave={(e)=>{borderTaker(e,"m5")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male5.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m6" onClick={(e)=>{avatarSelect(e,"male/male6.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m6")}} onMouseLeave={(e)=>{borderTaker(e,"m6")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male6.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m7" onClick={(e)=>{avatarSelect(e,"male/male7.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m7")}} onMouseLeave={(e)=>{borderTaker(e,"m7")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male7.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m8" onClick={(e)=>{avatarSelect(e,"male/male8.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m8")}} onMouseLeave={(e)=>{borderTaker(e,"m8")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male8.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m9" onClick={(e)=>{avatarSelect(e,"male/male9.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m9")}} onMouseLeave={(e)=>{borderTaker(e,"m9")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male9.jpg")}/>{/*each row should have 9 photos*/}
                
                </div>
                <div className="flexy">
                <img id="m10" onClick={(e)=>{avatarSelect(e,"male/male10.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m10")}} onMouseLeave={(e)=>{borderTaker(e,"m10")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male10.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m11" onClick={(e)=>{avatarSelect(e,"male/male11.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m11")}} onMouseLeave={(e)=>{borderTaker(e,"m11")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male11.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m12" onClick={(e)=>{avatarSelect(e,"male/male12.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m12")}} onMouseLeave={(e)=>{borderTaker(e,"m12")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male12.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m13" onClick={(e)=>{avatarSelect(e,"male/male13.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m13")}} onMouseLeave={(e)=>{borderTaker(e,"m13")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male13.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m14" onClick={(e)=>{avatarSelect(e,"male/male14.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m14")}} onMouseLeave={(e)=>{borderTaker(e,"m14")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male14.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m15" onClick={(e)=>{avatarSelect(e,"male/male15.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m15")}} onMouseLeave={(e)=>{borderTaker(e,"m15")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male15.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m16" onClick={(e)=>{avatarSelect(e,"male/male16.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m16")}} onMouseLeave={(e)=>{borderTaker(e,"m16")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male16.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m17" onClick={(e)=>{avatarSelect(e,"male/male17.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m17")}} onMouseLeave={(e)=>{borderTaker(e,"m17")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male17.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m18" onClick={(e)=>{avatarSelect(e,"male/male18.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m18")}} onMouseLeave={(e)=>{borderTaker(e,"m18")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male18.jpg")}/>{/*each row should have 9 photos*/}
                
                </div>

                <div className="flexy">
                <img id="m19" onClick={(e)=>{avatarSelect(e,"male/male19.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m19")}} onMouseLeave={(e)=>{borderTaker(e,"m19")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male19.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m20" onClick={(e)=>{avatarSelect(e,"male/male20.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m20")}} onMouseLeave={(e)=>{borderTaker(e,"m20")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male20.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m21" onClick={(e)=>{avatarSelect(e,"male/male21.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m21")}} onMouseLeave={(e)=>{borderTaker(e,"m21")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male21.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m22" onClick={(e)=>{avatarSelect(e,"male/male22.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m22")}} onMouseLeave={(e)=>{borderTaker(e,"m22")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male22.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m23" onClick={(e)=>{avatarSelect(e,"male/male23.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m23")}} onMouseLeave={(e)=>{borderTaker(e,"m23")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male23.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m24" onClick={(e)=>{avatarSelect(e,"male/male24.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m24")}} onMouseLeave={(e)=>{borderTaker(e,"m24")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male24.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m25" onClick={(e)=>{avatarSelect(e,"male/male25.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m25")}} onMouseLeave={(e)=>{borderTaker(e,"m25")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male25.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m26" onClick={(e)=>{avatarSelect(e,"male/male26.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m26")}} onMouseLeave={(e)=>{borderTaker(e,"m26")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male26.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m27" onClick={(e)=>{avatarSelect(e,"male/male27.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m27")}} onMouseLeave={(e)=>{borderTaker(e,"m27")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male27.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                <div className="flexy">
                <img id="m28" onClick={(e)=>{avatarSelect(e,"male/male28.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m28")}} onMouseLeave={(e)=>{borderTaker(e,"m28")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male28.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m29" onClick={(e)=>{avatarSelect(e,"male/male29.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m29")}} onMouseLeave={(e)=>{borderTaker(e,"m29")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male29.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m30" onClick={(e)=>{avatarSelect(e,"male/male30.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m30")}} onMouseLeave={(e)=>{borderTaker(e,"m30")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male30.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m31" onClick={(e)=>{avatarSelect(e,"male/male31.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m31")}} onMouseLeave={(e)=>{borderTaker(e,"m31")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male31.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m32" onClick={(e)=>{avatarSelect(e,"male/male32.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m32")}} onMouseLeave={(e)=>{borderTaker(e,"m32")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male32.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m33" onClick={(e)=>{avatarSelect(e,"male/male33.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m33")}} onMouseLeave={(e)=>{borderTaker(e,"m33")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male33.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m34" onClick={(e)=>{avatarSelect(e,"male/male34.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m34")}} onMouseLeave={(e)=>{borderTaker(e,"m34")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male34.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m35" onClick={(e)=>{avatarSelect(e,"male/male35.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m35")}} onMouseLeave={(e)=>{borderTaker(e,"m35")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male35.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m36" onClick={(e)=>{avatarSelect(e,"male/male36.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m36")}} onMouseLeave={(e)=>{borderTaker(e,"m36")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male36.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                <div className="flexy">
                <img id="m37" onClick={(e)=>{avatarSelect(e,"male/male37.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m37")}} onMouseLeave={(e)=>{borderTaker(e,"m37")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male37.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m38" onClick={(e)=>{avatarSelect(e,"male/male38.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m38")}} onMouseLeave={(e)=>{borderTaker(e,"m38")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male38.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m39" onClick={(e)=>{avatarSelect(e,"male/male39.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m39")}} onMouseLeave={(e)=>{borderTaker(e,"m39")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male39.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m40" onClick={(e)=>{avatarSelect(e,"male/male40.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m40")}} onMouseLeave={(e)=>{borderTaker(e,"m40")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male40.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m41" onClick={(e)=>{avatarSelect(e,"male/male41.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m41")}} onMouseLeave={(e)=>{borderTaker(e,"m41")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male41.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m42" onClick={(e)=>{avatarSelect(e,"male/male42.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m42")}} onMouseLeave={(e)=>{borderTaker(e,"m42")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male42.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m43" onClick={(e)=>{avatarSelect(e,"male/male43.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m43")}} onMouseLeave={(e)=>{borderTaker(e,"m43")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male43.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m44" onClick={(e)=>{avatarSelect(e,"male/male44.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m44")}} onMouseLeave={(e)=>{borderTaker(e,"m44")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male44.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m45" onClick={(e)=>{avatarSelect(e,"male/male45.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m45")}} onMouseLeave={(e)=>{borderTaker(e,"m45")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male45.jpg")}/>{/*each row should have 9 photos*/}
                </div>

                <div className="flexy">
                <img id="m46" onClick={(e)=>{avatarSelect(e,"male/male46.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m46")}} onMouseLeave={(e)=>{borderTaker(e,"m46")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male46.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m47" onClick={(e)=>{avatarSelect(e,"male/male47.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m47")}} onMouseLeave={(e)=>{borderTaker(e,"m47")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male47.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m48" onClick={(e)=>{avatarSelect(e,"male/male48.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m48")}} onMouseLeave={(e)=>{borderTaker(e,"m48")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male48.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m49" onClick={(e)=>{avatarSelect(e,"male/male49.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m49")}} onMouseLeave={(e)=>{borderTaker(e,"m49")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male49.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m50" onClick={(e)=>{avatarSelect(e,"male/male50.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m50")}} onMouseLeave={(e)=>{borderTaker(e,"m50")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male50.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m51" onClick={(e)=>{avatarSelect(e,"male/male51.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m51")}} onMouseLeave={(e)=>{borderTaker(e,"m51")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male51.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m52" onClick={(e)=>{avatarSelect(e,"male/male52.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m52")}} onMouseLeave={(e)=>{borderTaker(e,"m52")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male52.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m53" onClick={(e)=>{avatarSelect(e,"male/male53.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m53")}} onMouseLeave={(e)=>{borderTaker(e,"m53")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male53.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m54" onClick={(e)=>{avatarSelect(e,"male/male54.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m54")}} onMouseLeave={(e)=>{borderTaker(e,"m54")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male54.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                
                <div className="flexy">
                <img id="m55" onClick={(e)=>{avatarSelect(e,"male/male55.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m55")}} onMouseLeave={(e)=>{borderTaker(e,"m55")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male55.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m56" onClick={(e)=>{avatarSelect(e,"male/male56.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m56")}} onMouseLeave={(e)=>{borderTaker(e,"m56")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male56.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m57" onClick={(e)=>{avatarSelect(e,"male/male57.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m57")}} onMouseLeave={(e)=>{borderTaker(e,"m57")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male57.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m58" onClick={(e)=>{avatarSelect(e,"male/male58.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m58")}} onMouseLeave={(e)=>{borderTaker(e,"m58")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male58.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m59" onClick={(e)=>{avatarSelect(e,"male/male59.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m59")}} onMouseLeave={(e)=>{borderTaker(e,"m59")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male59.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m60" onClick={(e)=>{avatarSelect(e,"male/male60.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m60")}} onMouseLeave={(e)=>{borderTaker(e,"m60")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male60.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m61" onClick={(e)=>{avatarSelect(e,"male/male61.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m61")}} onMouseLeave={(e)=>{borderTaker(e,"m61")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male61.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m62" onClick={(e)=>{avatarSelect(e,"male/male62.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m62")}} onMouseLeave={(e)=>{borderTaker(e,"m62")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male62.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m63" onClick={(e)=>{avatarSelect(e,"male/male63.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m63")}} onMouseLeave={(e)=>{borderTaker(e,"m63")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male63.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                <div className="flexy">
                <img id="m64" onClick={(e)=>{avatarSelect(e,"male/male64.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m64")}} onMouseLeave={(e)=>{borderTaker(e,"m64")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male64.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m65" onClick={(e)=>{avatarSelect(e,"male/male65.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m65")}} onMouseLeave={(e)=>{borderTaker(e,"m65")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male65.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m66" onClick={(e)=>{avatarSelect(e,"male/male66.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m66")}} onMouseLeave={(e)=>{borderTaker(e,"m66")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male66.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m67" onClick={(e)=>{avatarSelect(e,"male/male67.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m67")}} onMouseLeave={(e)=>{borderTaker(e,"m67")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male67.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m68" onClick={(e)=>{avatarSelect(e,"male/male68.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m68")}} onMouseLeave={(e)=>{borderTaker(e,"m68")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male68.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m69" onClick={(e)=>{avatarSelect(e,"male/male69.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m69")}} onMouseLeave={(e)=>{borderTaker(e,"m69")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male69.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m70" onClick={(e)=>{avatarSelect(e,"male/male70.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m70")}} onMouseLeave={(e)=>{borderTaker(e,"m70")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male70.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m71" onClick={(e)=>{avatarSelect(e,"male/male71.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m71")}} onMouseLeave={(e)=>{borderTaker(e,"m71")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male71.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m72" onClick={(e)=>{avatarSelect(e,"male/male72.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m72")}} onMouseLeave={(e)=>{borderTaker(e,"m72")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male72.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                <div className="flexy">
                <img id="m73" onClick={(e)=>{avatarSelect(e,"male/male73.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m73")}} onMouseLeave={(e)=>{borderTaker(e,"m73")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male73.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m74" onClick={(e)=>{avatarSelect(e,"male/male74.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m74")}} onMouseLeave={(e)=>{borderTaker(e,"m74")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male74.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m75" onClick={(e)=>{avatarSelect(e,"male/male75.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m75")}} onMouseLeave={(e)=>{borderTaker(e,"m75")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male75.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m76" onClick={(e)=>{avatarSelect(e,"male/male76.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m76")}} onMouseLeave={(e)=>{borderTaker(e,"m76")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male76.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m77" onClick={(e)=>{avatarSelect(e,"male/male77.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m77")}} onMouseLeave={(e)=>{borderTaker(e,"m77")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male77.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m78" onClick={(e)=>{avatarSelect(e,"male/male78.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m78")}} onMouseLeave={(e)=>{borderTaker(e,"m78")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male78.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m79" onClick={(e)=>{avatarSelect(e,"male/male79.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m79")}} onMouseLeave={(e)=>{borderTaker(e,"m79")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male79.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m80" onClick={(e)=>{avatarSelect(e,"male/male80.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m80")}} onMouseLeave={(e)=>{borderTaker(e,"m80")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male80.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m81" onClick={(e)=>{avatarSelect(e,"male/male81.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m81")}} onMouseLeave={(e)=>{borderTaker(e,"m81")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male81.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                <div className="flexy">
                <img id="m82" onClick={(e)=>{avatarSelect(e,"male/male82.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m82")}} onMouseLeave={(e)=>{borderTaker(e,"m82")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male82.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m83" onClick={(e)=>{avatarSelect(e,"male/male83.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m83")}} onMouseLeave={(e)=>{borderTaker(e,"m83")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male83.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m84" onClick={(e)=>{avatarSelect(e,"male/male84.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m84")}} onMouseLeave={(e)=>{borderTaker(e,"m84")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male84.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m85" onClick={(e)=>{avatarSelect(e,"male/male85.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m85")}} onMouseLeave={(e)=>{borderTaker(e,"m85")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male85.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m86" onClick={(e)=>{avatarSelect(e,"male/male86.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m86")}} onMouseLeave={(e)=>{borderTaker(e,"m86")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male86.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m87" onClick={(e)=>{avatarSelect(e,"male/male87.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m87")}} onMouseLeave={(e)=>{borderTaker(e,"m87")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male87.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m88" onClick={(e)=>{avatarSelect(e,"male/male88.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m88")}} onMouseLeave={(e)=>{borderTaker(e,"m88")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male88.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m89" onClick={(e)=>{avatarSelect(e,"male/male89.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m89")}} onMouseLeave={(e)=>{borderTaker(e,"m89")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male89.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m90" onClick={(e)=>{avatarSelect(e,"male/male90.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m90")}} onMouseLeave={(e)=>{borderTaker(e,"m90")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male90.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                <div className="flexy">
                <img id="m91" onClick={(e)=>{avatarSelect(e,"male/male91.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m91")}} onMouseLeave={(e)=>{borderTaker(e,"m91")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male91.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m92" onClick={(e)=>{avatarSelect(e,"male/male92.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m92")}} onMouseLeave={(e)=>{borderTaker(e,"m92")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male92.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m93" onClick={(e)=>{avatarSelect(e,"male/male93.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m93")}} onMouseLeave={(e)=>{borderTaker(e,"m93")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male93.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m94" onClick={(e)=>{avatarSelect(e,"male/male94.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m94")}} onMouseLeave={(e)=>{borderTaker(e,"m94")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male94.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m95" onClick={(e)=>{avatarSelect(e,"male/male95.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m95")}} onMouseLeave={(e)=>{borderTaker(e,"m95")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male95.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m96" onClick={(e)=>{avatarSelect(e,"male/male96.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m96")}} onMouseLeave={(e)=>{borderTaker(e,"m96")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male96.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m97" onClick={(e)=>{avatarSelect(e,"male/male97.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m97")}} onMouseLeave={(e)=>{borderTaker(e,"m97")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male97.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m98" onClick={(e)=>{avatarSelect(e,"male/male98.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m98")}} onMouseLeave={(e)=>{borderTaker(e,"m98")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male98.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m99" onClick={(e)=>{avatarSelect(e,"male/male99.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m99")}} onMouseLeave={(e)=>{borderTaker(e,"m99")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male99.jpg")}/>{/*each row should have 9 photos*/}
                </div>

                <div className="flexy">
                <img id="m100" onClick={(e)=>{avatarSelect(e,"male/male100.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m100")}} onMouseLeave={(e)=>{borderTaker(e,"m100")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male100.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m101" onClick={(e)=>{avatarSelect(e,"male/male101.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m101")}} onMouseLeave={(e)=>{borderTaker(e,"m101")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male101.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m102" onClick={(e)=>{avatarSelect(e,"male/male102.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m102")}} onMouseLeave={(e)=>{borderTaker(e,"m102")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male102.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m103" onClick={(e)=>{avatarSelect(e,"male/male103.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m103")}} onMouseLeave={(e)=>{borderTaker(e,"m103")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male103.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m104" onClick={(e)=>{avatarSelect(e,"male/male104.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m104")}} onMouseLeave={(e)=>{borderTaker(e,"m104")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male104.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m105" onClick={(e)=>{avatarSelect(e,"male/male105.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m105")}} onMouseLeave={(e)=>{borderTaker(e,"m105")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male105.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m106" onClick={(e)=>{avatarSelect(e,"male/male106.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m106")}} onMouseLeave={(e)=>{borderTaker(e,"m106")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male106.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m107" onClick={(e)=>{avatarSelect(e,"male/male107.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m107")}} onMouseLeave={(e)=>{borderTaker(e,"m107")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male107.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m108" onClick={(e)=>{avatarSelect(e,"male/male108.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m108")}} onMouseLeave={(e)=>{borderTaker(e,"m108")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male108.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                

                <div className="flexy">
                <img id="m109" onClick={(e)=>{avatarSelect(e,"male/male108.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m109")}} onMouseLeave={(e)=>{borderTaker(e,"m109")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male109.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m110" onClick={(e)=>{avatarSelect(e,"male/male108.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m110")}} onMouseLeave={(e)=>{borderTaker(e,"m110")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male110.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m111" onClick={(e)=>{avatarSelect(e,"male/male108.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m111")}} onMouseLeave={(e)=>{borderTaker(e,"m111")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male111.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m112" onClick={(e)=>{avatarSelect(e,"male/male108.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m112")}} onMouseLeave={(e)=>{borderTaker(e,"m112")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male112.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m113" onClick={(e)=>{avatarSelect(e,"male/male108.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m113")}} onMouseLeave={(e)=>{borderTaker(e,"m113")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male113.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m114" onClick={(e)=>{avatarSelect(e,"male/male108.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m114")}} onMouseLeave={(e)=>{borderTaker(e,"m114")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male114.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m115" onClick={(e)=>{avatarSelect(e,"male/male108.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m115")}} onMouseLeave={(e)=>{borderTaker(e,"m115")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male115.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m116" onClick={(e)=>{avatarSelect(e,"male/male108.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m116")}} onMouseLeave={(e)=>{borderTaker(e,"m116")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male116.jpg")}/>{/*each row should have 9 photos*/}
                <img id="m117" onClick={(e)=>{avatarSelect(e,"male/male108.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"m117")}} onMouseLeave={(e)=>{borderTaker(e,"m117")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/male/male117.jpg")}/>{/*each row should have 9 photos*/}
                </div>


            </div>

            <div className="contain" style={{backgroundColor:"black",height:500, width:1500,marginTop:20, overflow:"scroll", overflowX:"hidden"}}>
                <h3 style={{color:"white"}}>Female</h3>
                <div className="flexy">
                <img id="f1" onClick={(e)=>{avatarSelect(e,"female/female1.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f1")}} onMouseLeave={(e)=>{borderTaker(e,"f1")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female1.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f2" onClick={(e)=>{avatarSelect(e,"female/female2.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f2")}} onMouseLeave={(e)=>{borderTaker(e,"f2")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female2.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f3" onClick={(e)=>{avatarSelect(e,"female/female3.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f3")}} onMouseLeave={(e)=>{borderTaker(e,"f3")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female3.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f4" onClick={(e)=>{avatarSelect(e,"female/female4.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f4")}} onMouseLeave={(e)=>{borderTaker(e,"f4")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female4.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f5" onClick={(e)=>{avatarSelect(e,"female/female5.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f5")}} onMouseLeave={(e)=>{borderTaker(e,"f5")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female5.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f6" onClick={(e)=>{avatarSelect(e,"female/female6.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f6")}} onMouseLeave={(e)=>{borderTaker(e,"f6")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female6.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f7" onClick={(e)=>{avatarSelect(e,"female/female7.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f7")}} onMouseLeave={(e)=>{borderTaker(e,"f7")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female7.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f8" onClick={(e)=>{avatarSelect(e,"female/female8.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f8")}} onMouseLeave={(e)=>{borderTaker(e,"f8")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female8.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f9" onClick={(e)=>{avatarSelect(e,"female/female9.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f9")}} onMouseLeave={(e)=>{borderTaker(e,"f9")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female9.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                

                <div className="flexy">
                <img id="f10" onClick={(e)=>{avatarSelect(e,"female/female10.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f10")}} onMouseLeave={(e)=>{borderTaker(e,"f10")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female10.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f11" onClick={(e)=>{avatarSelect(e,"female/female11.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f11")}} onMouseLeave={(e)=>{borderTaker(e,"f11")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female11.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f12" onClick={(e)=>{avatarSelect(e,"female/female12.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f12")}} onMouseLeave={(e)=>{borderTaker(e,"f12")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female12.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f13" onClick={(e)=>{avatarSelect(e,"female/female13.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f13")}} onMouseLeave={(e)=>{borderTaker(e,"f13")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female13.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f14" onClick={(e)=>{avatarSelect(e,"female/female14.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f14")}} onMouseLeave={(e)=>{borderTaker(e,"f14")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female14.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f15" onClick={(e)=>{avatarSelect(e,"female/female15.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f15")}} onMouseLeave={(e)=>{borderTaker(e,"f15")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female15.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f16" onClick={(e)=>{avatarSelect(e,"female/female16.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f16")}} onMouseLeave={(e)=>{borderTaker(e,"f16")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female16.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f17" onClick={(e)=>{avatarSelect(e,"female/female17.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f17")}} onMouseLeave={(e)=>{borderTaker(e,"f17")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female17.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f18" onClick={(e)=>{avatarSelect(e,"female/female18.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f18")}} onMouseLeave={(e)=>{borderTaker(e,"f18")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female18.jpg")}/>{/*each row should have 9 photos*/}
                </div>

                <div className="flexy">
                <img id="f19" onClick={(e)=>{avatarSelect(e,"female/female19.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f19")}} onMouseLeave={(e)=>{borderTaker(e,"f19")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female19.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f20" onClick={(e)=>{avatarSelect(e,"female/female20.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f20")}} onMouseLeave={(e)=>{borderTaker(e,"f20")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female20.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f21" onClick={(e)=>{avatarSelect(e,"female/female21.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f21")}} onMouseLeave={(e)=>{borderTaker(e,"f21")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female21.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f22" onClick={(e)=>{avatarSelect(e,"female/female22.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f22")}} onMouseLeave={(e)=>{borderTaker(e,"f22")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female22.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f23" onClick={(e)=>{avatarSelect(e,"female/female23.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f23")}} onMouseLeave={(e)=>{borderTaker(e,"f23")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female23.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f24" onClick={(e)=>{avatarSelect(e,"female/female24.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f24")}} onMouseLeave={(e)=>{borderTaker(e,"f24")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female24.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f25" onClick={(e)=>{avatarSelect(e,"female/female25.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f25")}} onMouseLeave={(e)=>{borderTaker(e,"f25")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female25.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f26" onClick={(e)=>{avatarSelect(e,"female/female26.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f26")}} onMouseLeave={(e)=>{borderTaker(e,"f26")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female26.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f27" onClick={(e)=>{avatarSelect(e,"female/female27.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f27")}} onMouseLeave={(e)=>{borderTaker(e,"f27")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female27.jpg")}/>{/*each row should have 9 photos*/}
                </div>

                <div className="flexy">
                <img id="f28" onClick={(e)=>{avatarSelect(e,"female/female28.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f28")}} onMouseLeave={(e)=>{borderTaker(e,"f28")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female28.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f29" onClick={(e)=>{avatarSelect(e,"female/female29.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f29")}} onMouseLeave={(e)=>{borderTaker(e,"f29")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female29.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f30" onClick={(e)=>{avatarSelect(e,"female/female30.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f30")}} onMouseLeave={(e)=>{borderTaker(e,"f30")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female30.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f31" onClick={(e)=>{avatarSelect(e,"female/female31.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f31")}} onMouseLeave={(e)=>{borderTaker(e,"f31")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female31.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f32" onClick={(e)=>{avatarSelect(e,"female/female32.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f32")}} onMouseLeave={(e)=>{borderTaker(e,"f32")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female32.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f33" onClick={(e)=>{avatarSelect(e,"female/female33.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f33")}} onMouseLeave={(e)=>{borderTaker(e,"f33")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female33.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f34" onClick={(e)=>{avatarSelect(e,"female/female34.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f34")}} onMouseLeave={(e)=>{borderTaker(e,"f34")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female34.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f35" onClick={(e)=>{avatarSelect(e,"female/female35.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f35")}} onMouseLeave={(e)=>{borderTaker(e,"f35")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female35.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f36" onClick={(e)=>{avatarSelect(e,"female/female36.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f36")}} onMouseLeave={(e)=>{borderTaker(e,"f36")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female36.jpg")}/>{/*each row should have 9 photos*/}
                </div>

                <div className="flexy">
                <img id="f37" onClick={(e)=>{avatarSelect(e,"female/female37.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f37")}} onMouseLeave={(e)=>{borderTaker(e,"f37")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female37.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f38" onClick={(e)=>{avatarSelect(e,"female/female38.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f38")}} onMouseLeave={(e)=>{borderTaker(e,"f38")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female38.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f39" onClick={(e)=>{avatarSelect(e,"female/female39.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f39")}} onMouseLeave={(e)=>{borderTaker(e,"f39")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female39.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f40" onClick={(e)=>{avatarSelect(e,"female/female40.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f40")}} onMouseLeave={(e)=>{borderTaker(e,"f40")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female40.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f41" onClick={(e)=>{avatarSelect(e,"female/female41.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f41")}} onMouseLeave={(e)=>{borderTaker(e,"f41")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female41.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f42" onClick={(e)=>{avatarSelect(e,"female/female42.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f42")}} onMouseLeave={(e)=>{borderTaker(e,"f42")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female42.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f43" onClick={(e)=>{avatarSelect(e,"female/female43.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f43")}} onMouseLeave={(e)=>{borderTaker(e,"f43")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female43.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f44" onClick={(e)=>{avatarSelect(e,"female/female44.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f44")}} onMouseLeave={(e)=>{borderTaker(e,"f44")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female44.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f45" onClick={(e)=>{avatarSelect(e,"female/female45.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f45")}} onMouseLeave={(e)=>{borderTaker(e,"f45")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female45.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                <div className="flexy">
                <img id="f46" onClick={(e)=>{avatarSelect(e,"female/female46.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f46")}} onMouseLeave={(e)=>{borderTaker(e,"f46")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female46.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f47" onClick={(e)=>{avatarSelect(e,"female/female47.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f47")}} onMouseLeave={(e)=>{borderTaker(e,"f47")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female47.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f48" onClick={(e)=>{avatarSelect(e,"female/female48.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f48")}} onMouseLeave={(e)=>{borderTaker(e,"f48")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female48.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f49" onClick={(e)=>{avatarSelect(e,"female/female49.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f49")}} onMouseLeave={(e)=>{borderTaker(e,"f49")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female49.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f50" onClick={(e)=>{avatarSelect(e,"female/female50.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f50")}} onMouseLeave={(e)=>{borderTaker(e,"f50")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female50.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f51" onClick={(e)=>{avatarSelect(e,"female/female51.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f51")}} onMouseLeave={(e)=>{borderTaker(e,"f51")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female51.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f52" onClick={(e)=>{avatarSelect(e,"female/female52.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f52")}} onMouseLeave={(e)=>{borderTaker(e,"f52")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female52.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f53" onClick={(e)=>{avatarSelect(e,"female/female53.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f53")}} onMouseLeave={(e)=>{borderTaker(e,"f53")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female53.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f54" onClick={(e)=>{avatarSelect(e,"female/female54.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f54")}} onMouseLeave={(e)=>{borderTaker(e,"f54")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female54.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                <div className="flexy">
                <img id="f55" onClick={(e)=>{avatarSelect(e,"female/female55.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f55")}} onMouseLeave={(e)=>{borderTaker(e,"f55")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female55.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f56" onClick={(e)=>{avatarSelect(e,"female/female56.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f56")}} onMouseLeave={(e)=>{borderTaker(e,"f56")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female56.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f57" onClick={(e)=>{avatarSelect(e,"female/female57.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f57")}} onMouseLeave={(e)=>{borderTaker(e,"f57")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female57.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f58" onClick={(e)=>{avatarSelect(e,"female/female58.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f58")}} onMouseLeave={(e)=>{borderTaker(e,"f58")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female58.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f59" onClick={(e)=>{avatarSelect(e,"female/female59.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f59")}} onMouseLeave={(e)=>{borderTaker(e,"f59")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female59.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f60" onClick={(e)=>{avatarSelect(e,"female/female60.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f60")}} onMouseLeave={(e)=>{borderTaker(e,"f60")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female60.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f61" onClick={(e)=>{avatarSelect(e,"female/female61.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f61")}} onMouseLeave={(e)=>{borderTaker(e,"f61")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female61.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f62" onClick={(e)=>{avatarSelect(e,"female/female62.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f62")}} onMouseLeave={(e)=>{borderTaker(e,"f62")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female62.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f63" onClick={(e)=>{avatarSelect(e,"female/female63.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f63")}} onMouseLeave={(e)=>{borderTaker(e,"f63")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female63.jpg")}/>{/*each row should have 9 photos*/}
                </div>

                <div className="flexy">
                <img id="f64" onClick={(e)=>{avatarSelect(e,"female/female64.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f64")}} onMouseLeave={(e)=>{borderTaker(e,"f64")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female64.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f65" onClick={(e)=>{avatarSelect(e,"female/female65.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f65")}} onMouseLeave={(e)=>{borderTaker(e,"f65")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female65.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f66" onClick={(e)=>{avatarSelect(e,"female/female66.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f66")}} onMouseLeave={(e)=>{borderTaker(e,"f66")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female66.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f67" onClick={(e)=>{avatarSelect(e,"female/female67.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f67")}} onMouseLeave={(e)=>{borderTaker(e,"f67")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female67.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f68" onClick={(e)=>{avatarSelect(e,"female/female68.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f68")}} onMouseLeave={(e)=>{borderTaker(e,"f68")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female68.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f69" onClick={(e)=>{avatarSelect(e,"female/female69.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f69")}} onMouseLeave={(e)=>{borderTaker(e,"f69")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female69.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f70" onClick={(e)=>{avatarSelect(e,"female/female70.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f70")}} onMouseLeave={(e)=>{borderTaker(e,"f70")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female70.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f71" onClick={(e)=>{avatarSelect(e,"female/female71.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f71")}} onMouseLeave={(e)=>{borderTaker(e,"f71")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female71.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f72" onClick={(e)=>{avatarSelect(e,"female/female72.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f72")}} onMouseLeave={(e)=>{borderTaker(e,"f72")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female72.jpg")}/>{/*each row should have 9 photos*/}
                </div>
                <div className="flexy">
                <img id="f73" onClick={(e)=>{avatarSelect(e,"female/female73.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f73")}} onMouseLeave={(e)=>{borderTaker(e,"f73")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female73.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f74" onClick={(e)=>{avatarSelect(e,"female/female74.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f74")}} onMouseLeave={(e)=>{borderTaker(e,"f74")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female74.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f75" onClick={(e)=>{avatarSelect(e,"female/female75.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f75")}} onMouseLeave={(e)=>{borderTaker(e,"f75")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female75.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f76" onClick={(e)=>{avatarSelect(e,"female/female76.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f76")}} onMouseLeave={(e)=>{borderTaker(e,"f76")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female76.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f77" onClick={(e)=>{avatarSelect(e,"female/female77.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f77")}} onMouseLeave={(e)=>{borderTaker(e,"f77")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female77.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f78" onClick={(e)=>{avatarSelect(e,"female/female78.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f78")}} onMouseLeave={(e)=>{borderTaker(e,"f78")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female78.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f79" onClick={(e)=>{avatarSelect(e,"female/female79.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f79")}} onMouseLeave={(e)=>{borderTaker(e,"f79")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female79.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f80" onClick={(e)=>{avatarSelect(e,"female/female80.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f80")}} onMouseLeave={(e)=>{borderTaker(e,"f80")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female80.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f81" onClick={(e)=>{avatarSelect(e,"female/female81.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f81")}} onMouseLeave={(e)=>{borderTaker(e,"f81")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female81.jpg")}/>{/*each row should have 9 photos*/}
                </div>

                <div className="flexy">
                <img id="f82" onClick={(e)=>{avatarSelect(e,"female/female82.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f82")}} onMouseLeave={(e)=>{borderTaker(e,"f82")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female82.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f83" onClick={(e)=>{avatarSelect(e,"female/female83.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f83")}} onMouseLeave={(e)=>{borderTaker(e,"f83")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female83.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f84" onClick={(e)=>{avatarSelect(e,"female/female84.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f84")}} onMouseLeave={(e)=>{borderTaker(e,"f84")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female84.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f85" onClick={(e)=>{avatarSelect(e,"female/female85.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f85")}} onMouseLeave={(e)=>{borderTaker(e,"f85")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female85.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f86" onClick={(e)=>{avatarSelect(e,"female/female86.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f86")}} onMouseLeave={(e)=>{borderTaker(e,"f86")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female86.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f87" onClick={(e)=>{avatarSelect(e,"female/female87.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f87")}} onMouseLeave={(e)=>{borderTaker(e,"f87")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female87.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f88" onClick={(e)=>{avatarSelect(e,"female/female88.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f88")}} onMouseLeave={(e)=>{borderTaker(e,"f88")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female88.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f89" onClick={(e)=>{avatarSelect(e,"female/female89.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f89")}} onMouseLeave={(e)=>{borderTaker(e,"f89")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female89.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f90" onClick={(e)=>{avatarSelect(e,"female/female90.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f90")}} onMouseLeave={(e)=>{borderTaker(e,"f90")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female90.jpg")}/>{/*each row should have 9 photos*/}
                </div>

                <div className="flexy">
                <img id="f91" onClick={(e)=>{avatarSelect(e,"female/female91.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f91")}} onMouseLeave={(e)=>{borderTaker(e,"f91")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female91.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f92" onClick={(e)=>{avatarSelect(e,"female/female92.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f92")}} onMouseLeave={(e)=>{borderTaker(e,"f92")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female92.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f93" onClick={(e)=>{avatarSelect(e,"female/female93.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f93")}} onMouseLeave={(e)=>{borderTaker(e,"f93")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female93.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f94" onClick={(e)=>{avatarSelect(e,"female/female94.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f94")}} onMouseLeave={(e)=>{borderTaker(e,"f94")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female94.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f95" onClick={(e)=>{avatarSelect(e,"female/female95.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f95")}} onMouseLeave={(e)=>{borderTaker(e,"f95")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female95.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f96" onClick={(e)=>{avatarSelect(e,"female/female96.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f96")}} onMouseLeave={(e)=>{borderTaker(e,"f96")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female96.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f97" onClick={(e)=>{avatarSelect(e,"female/female97.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f97")}} onMouseLeave={(e)=>{borderTaker(e,"f97")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female97.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f98" onClick={(e)=>{avatarSelect(e,"female/female98.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f98")}} onMouseLeave={(e)=>{borderTaker(e,"f98")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female98.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f99" onClick={(e)=>{avatarSelect(e,"female/female99.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f99")}} onMouseLeave={(e)=>{borderTaker(e,"f99")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female99.jpg")}/>{/*each row should have 9 photos*/}
                </div>


                <div className="flexy">
                <img id="f100" onClick={(e)=>{avatarSelect(e,"female/female100.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f100")}} onMouseLeave={(e)=>{borderTaker(e,"f100")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female100.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f101" onClick={(e)=>{avatarSelect(e,"female/female101.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f101")}} onMouseLeave={(e)=>{borderTaker(e,"f101")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female101.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f102" onClick={(e)=>{avatarSelect(e,"female/female102.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f102")}} onMouseLeave={(e)=>{borderTaker(e,"f102")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female102.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f103" onClick={(e)=>{avatarSelect(e,"female/female103.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f103")}} onMouseLeave={(e)=>{borderTaker(e,"f103")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female103.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f104" onClick={(e)=>{avatarSelect(e,"female/female104.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f104")}} onMouseLeave={(e)=>{borderTaker(e,"f104")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female104.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f105" onClick={(e)=>{avatarSelect(e,"female/female105.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f105")}} onMouseLeave={(e)=>{borderTaker(e,"f105")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female105.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f106" onClick={(e)=>{avatarSelect(e,"female/female106.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f106")}} onMouseLeave={(e)=>{borderTaker(e,"f106")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female106.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f107" onClick={(e)=>{avatarSelect(e,"female/female107.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f107")}} onMouseLeave={(e)=>{borderTaker(e,"f107")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female107.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f108" onClick={(e)=>{avatarSelect(e,"female/female108.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f108")}} onMouseLeave={(e)=>{borderTaker(e,"f108")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female108.jpg")}/>{/*each row should have 9 photos*/}
                </div>

                <div className="flexy">
                <img id="f109" onClick={(e)=>{avatarSelect(e,"female/female109.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f109")}} onMouseLeave={(e)=>{borderTaker(e,"f109")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female109.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f110" onClick={(e)=>{avatarSelect(e,"female/female110.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f110")}} onMouseLeave={(e)=>{borderTaker(e,"f110")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female110.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f111" onClick={(e)=>{avatarSelect(e,"female/female111.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f111")}} onMouseLeave={(e)=>{borderTaker(e,"f111")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female111.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f112" onClick={(e)=>{avatarSelect(e,"female/female112.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f112")}} onMouseLeave={(e)=>{borderTaker(e,"f112")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female112.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f113" onClick={(e)=>{avatarSelect(e,"female/female113.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f113")}} onMouseLeave={(e)=>{borderTaker(e,"f113")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female113.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f114" onClick={(e)=>{avatarSelect(e,"female/female114.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f114")}} onMouseLeave={(e)=>{borderTaker(e,"f114")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female114.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f115" onClick={(e)=>{avatarSelect(e,"female/female115.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f115")}} onMouseLeave={(e)=>{borderTaker(e,"f115")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female115.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f116" onClick={(e)=>{avatarSelect(e,"female/female116.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f116")}} onMouseLeave={(e)=>{borderTaker(e,"f116")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female116.jpg")}/>{/*each row should have 9 photos*/}
                <img id="f117" onClick={(e)=>{avatarSelect(e,"female/female117.jpg")}} onMouseEnter={(e)=>{borderGiver(e,"f117")}} onMouseLeave={(e)=>{borderTaker(e,"f117")}} style={{height:150,width:150,marginLeft:5,marginRight:5, marginTop:5,marginBottom:5}} src={require("../photos/pictures/female/female117.jpg")}/>{/*each row should have 9 photos*/}
                </div>

            </div>
        </div>
    )

}

export default Avatar